# Generated by Django 5.0.1 on 2024-02-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkbox_model', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rusnounsmorfs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=60)),
                ('code', models.IntegerField()),
                ('code_parent', models.IntegerField()),
                ('plural', models.SmallIntegerField()),
                ('gender', models.CharField(max_length=3)),
                ('wcase', models.CharField(max_length=4)),
                ('soul', models.SmallIntegerField()),
            ],
        ),
    ]
