# Generated by Django 5.0.1 on 2024-02-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('mood_type', models.CharField(max_length=20)),
                ('part_of_speech', models.CharField(max_length=20)),
                ('alive', models.BooleanField()),
            ],
        ),
    ]
