# Generated by Django 5.0.1 on 2024-02-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_allwords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allwords',
        ),
    ]
