# Generated by Django 5.0.1 on 2024-02-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_allwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allwords',
            name='type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
