# Generated by Django 5.0.1 on 2024-02-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_allwords_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allwords',
            name='comp',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='face',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='inf',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='kind',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='nakl',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='perfect',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='short',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='time',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='transit',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='type_ssub',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='type_sub',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='vozv',
            field=models.SmallIntegerField(blank=True),
        ),
    ]
