# Generated by Django 5.0.1 on 2024-02-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_allwords_comp_alter_allwords_face_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allwords',
            name='comp',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='face',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='inf',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='kind',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='nakl',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='perfect',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='short',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='time',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='transit',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='type_ssub',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='type_sub',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='vozv',
            field=models.SmallIntegerField(null=True),
        ),
    ]
