# Generated by Django 5.0.1 on 2024-02-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_allwords_comp_alter_allwords_face_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allwords',
            name='gender',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='plural',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='soul',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='allwords',
            name='wcase',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
